version: "3"
services:
  nginx:
    image: mynginx
    build:
      dockerfile: Dockerfile
      context: . 
    container_name: nginx-http-reverse-proxy
    env_file:
      - nginx.env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
