version: "3"
services:
  nginx:
    image: fabiocicerchia/nginx-lua
    build:
      dockerfile: Dockerfile
      context: .
    container_name: nginx-http-reverse-proxy
    env_file:
      - nginx.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
      - ./nginx.conf:/etc/nginx/nginx.conf